export const INACTIVE_PROJECT_STATUS = 'INACTIVE';
export const ACTIVE_PROJECT_STATUS = 'ACTIVE';
export const COMPLETED_PROJECT_STATUS = 'COMPLETED';
export const ON_HOLD_PROJECT_STATUS = 'ON_HOLD';

export const FETCH_PROJECT_LIST = 'PROJECT/FETCH_PROJECT_LIST';
export const FETCH_PROJECT_LIST_SUCCESS = 'PROJECT/FETCH_PROJECT_LIST_SUCCESS';
export const FETCH_PROJECT_LIST_FAILURE = 'PROJECT/FETCH_PROJECT_LIST_FAILURE';

export const CHANGE_STATUS_PROJECT = 'PROJECT/CHANGE_STATUS_PROJECT';
export const CHANGE_STATUS_PROJECT_SUCCESS =
  'PROJECT/CHANGE_STATUS_PROJECT_SUCCESS';
export const CHANGE_STATUS_PROJECT_FAILURE =
  'PROJECT/CHANGE_STATUS_PROJECT_FAILURE';
export const SELECT_PROJECT_ITEM = 'PROJECT/SELECT_PROJECT_ITEM';

export const SET_ACTIVE_PROJECT = 'PROJECT/SET_ACTIVE_PROJECT';
export const SET_ACTIVE_PROJECT_SUCCESS = 'PROJECT/SET_ACTIVE_PROJECT_SUCCESS';
export const SET_ACTIVE_PROJECT_FAILURE = 'PROJECT/SET_ACTIVE_PROJECT_FAILURE';

export const SET_INACTIVE_PROJECT = 'PROJECT/SET_INACTIVE_PROJECT';
export const SET_INACTIVE_PROJECT_SUCCESS =
  'PROJECT/SET_INACTIVE_PROJECT_SUCCESS';
export const SET_INACTIVE_PROJECT_FAILURE =
  'PROJECT/SET_INACTIVE_PROJECT_FAILURE';

export const UPDATE_LAST_ACTION = 'PROJECT/UPDATE_LAST_ACTION';
export const UPDATE_SEARCH_STR = 'PROJECT/UPDATE_SEARCH_STR';
export const CLEAR_SEARCH_FORM = 'PROJECT/CLEAR_SEARCH_FORM';
