export const USER_ROLE = {
  ADMIN: 'ROLE_ADMIN',
  USER: 'ROLE_USER',
};

export const USER_TITLE = {
  QA: 'QA',
};

export const PROJECT_STATUS_TYPE = {
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  ON_HOLD: 'ON_HOLD',
};

export const SYS_ADMIN_ROLE = 'ADMIN';
export const NORMAL_USER_ROLE = 'NORMAL_USER_ROLE';

export const LOGIN_REDUX_KEY = 'login';
export const PROFILE_MENU_KEY = 'ProfileMenu';

export const LOGIN = 'USER/LOGIN';
export const LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'USER/LOGIN_FAILED';

export const LOGOUT = 'USER/LOGOUT';
export const LOGOUT_SUCCESS = 'USER/LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'USER/LOGOUT_FAILED';

export const SET_USER_PROFILE = 'USER/SET_USER_PROFILE';
export const SET_PROJECT_INFO = 'USER/SET_PROJECT_INFO';

export const SET_MENU_PATHS = 'USER/SET_MENU_PATHS';

export const LOAD_AUTH_INFO_FROM_STORAGE = 'USER/LOAD_AUTH_INFO_FROM_STORAGE';

export const CLEAR_APP_STATE = 'USER/CLEAR_APP_STATE';

export const GET_CURRENT_USER_DATA = 'USER/GET_CURRENT_USER_DATA';
export const GET_CURRENT_USER_DATA_SUCCESS =
  'USER/GET_CURRENT_USER_DATA_SUCCESS';
export const GET_CURRENT_USER_DATA_FAILURE =
  'USER/GET_CURRENT_USER_DATA_FAILURE';

export const FETCH_USER_LIST_ASSIGN = 'USER/FETCH_USER_LIST_ASSIGN';
export const FETCH_USER_LIST_ASSIGN_SUCCESS =
  'USER/FETCH_USER_LIST_ASSIGN_SUCCESS';
export const FETCH_USER_LIST_ASSIGN_FAILURE =
  'USER/FETCH_USER_LIST_ASSIGN_FAILURE';

export const FETCH_USER_LIST = 'USER/FETCH_USER_LIST';
export const FETCH_USER_LIST_SUCCESS = 'USER/FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILURE = 'USER/FETCH_USER_LIST_FAILURE';

export const RESET_LIST_ASSIGNEE = 'USER/RESET_LIST_ASSIGNEE';

export const CHANGE_PASSWORD = 'USER/CHANGE_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const USER_STATUS = {
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED',
  ACTIVE: 'ACTIVE',
};
